input_number:
  ph_last_valid:
    name: Last valid pH
    min: 0
    max: 14
    step: 0.01
    unit_of_measurement: "pH"
    mode: box
  orp_last_valid:
    name: Last valid ORP
    min: 0
    max: 2000
    step: 1
    unit_of_measurement: "mV"
    mode: box
  temperature_last_valid:
    name: Last valid Temperature
    min: 0
    max: 120
    step: 0.1
    unit_of_measurement: "°F"
    mode: box
  tds_last_valid:
    name: Last valid TDS
    min: 0
    max: 10000
    step: 10
    unit_of_measurement: "ppm"
    mode: box
  conductivity_last_valid:
    name: Last valid Conductivity
    min: 0
    max: 20000
    step: 100
    unit_of_measurement: "µS/cm"
    mode: box
  salinity_last_valid:
    name: Last valid Salinity
    min: 0
    max: 10000
    step: 10
    unit_of_measurement: "ppm"
    mode: box
  density_last_valid:
    name: Last valid Specific Gravity
    min: 0.9
    max: 1.1
    step: 0.001
    unit_of_measurement: "SG"
    mode: box
